on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v8
        with:
          script: |
            const script = require('./onPush.js')
            console.log(script({github, context}))